# Generated by Django 5.2.3 on 2025-06-30 08:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0004_crewmemberposition_crewmember"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="crewmember",
            options={
                "ordering": ["first_name", "last_name"],
                "verbose_name": "Crew Member",
                "verbose_name_plural": "Crew Members",
            },
        ),
        migrations.AddField(
            model_name="airplane",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
        migrations.AddField(
            model_name="airport",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
