# Generated by Django 5.2.3 on 2025-06-30 09:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0005_alter_crewmember_options_airplane_image_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="airplane",
            options={
                "ordering": ["name"],
                "verbose_name": "Airplane",
                "verbose_name_plural": "Airplanes",
            },
        ),
        migrations.RemoveField(
            model_name="airplane",
            name="rows",
        ),
        migrations.RemoveField(
            model_name="airplane",
            name="seats_in_row",
        ),
        migrations.CreateModel(
            name="AirplaneSeatConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seat_class",
                    models.CharField(
                        choices=[("economy", "Economy"), ("business", "Business")],
                        max_length=10,
                    ),
                ),
                (
                    "rows",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(500),
                        ]
                    ),
                ),
                (
                    "seats_in_row",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(500),
                        ]
                    ),
                ),
                (
                    "airplane",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seat_configurations",
                        to="airport.airplane",
                    ),
                ),
            ],
            options={
                "verbose_name": "Airplane Seat Configuration",
                "verbose_name_plural": "Airplane Seat Configurations",
                "ordering": ["seat_class", "rows", "seats_in_row"],
            },
        ),
    ]
