# Generated by Django 5.2.3 on 2025-06-30 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0006_alter_airplane_options_remove_airplane_rows_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="airplaneseatconfiguration",
            unique_together={("airplane", "seat_class")},
        ),
    ]
